name: Build & Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: bhhhh   # <-- App Service name only (no domain)
  PYTHON_VERSION: "3.11"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # (optional) quick validation build so requirements errors fail early
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip artifact
        run: |
          zip -r release.zip . \
            -x "**/.git*" "**/__pycache__*" "**/.venv*" "**/env*" "*.pyc"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}                 # <- must be the name only
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # full XML pasted as a secret
          package: release.zip
